### ISSUE TITLE
Possible to watch src/images to trigger when images added/removed?

### ISSUE THREAD

**Issue by mikeerickson** [greypants/gulp-starter#106]
Curious if it is possible to add a watch task to watch the src/images directory and trigger gulp images when changes occur (add, edit, delete image)

**Comment by greypants** [comment]
Absolutely. It's fixed in the [2.0 branch](https://github.com/greypants/gulp-starter/tree/2.0) using the [`gulp-watch` plugin](https://github.com/greypants/gulp-starter/blob/2.0/gulpfile.js/tasks/watch.js#L3). There's a whole slew of changes/improvements in there. It's starting to settle, and should be merged in the next couple weeks.

**Comment by mikeerickson** [comment]
Hmm, I thought I was using the 2.0 branch already, but maybe not. I will have a closer look tomorrow.

Lots of good stuff in there, promoted me to refactor my existing workflow to follow the basic construct you have 

Also, like to "trickery" of the gulpfile.js folder with all the core stuff in the folder.

**Comment by greypants** [comment]
:+1: Yeah that gulpfile.js folder is fun. Definitely let me know if new files aren't being picked up. The should be.

**Comment by greypants** [comment]
Working for me in the latest (merging soon)
