### ISSUE TITLE
BrowserSync not reloading

### ISSUE THREAD

**Issue by gandhiShepard** [greypants/gulp-starter#110]
This works great when I run `gulp`, but when I update the HTML or Sass, the browser doesn't refresh. And even if I force the browser to refresh, the updates still don't appear. Am I doing something wrong? I'm not getting any errors. JS reloads as expected, but nothing else does. Please advise.

**Comment by mehtmehtsen** [comment]
I've got exactly the same issue!

Not using a static server, though. Instead I'm proxying a vhost.
In my config.js I changed static server to
```javascript
browserSync: {
    conf: {
      proxy: "http://kiosk.dev:8888",                  
      files: ['site/**/*.php', 'assets/js/**/*.js']
    }
}
```
and to load my `conf` in browserSync.js I changed the argument for `browserSync()` to `config.conf`. I hope all this makes sense. ^^
When I add `'assets/scss/**/*.scss'` to `files` at least I get `File changed: C:\wamp\www\kiosk-framework\assets\scss\05_base\_base.scss`, otherwise there is nothing at all.

It seems to me the watch task isn't even started - I added a `console.log()` which never appears.
I also added a `console.log()` to my sass-task which only appears when I startup gulp, but not when saving changes to my scss-files.

Any help would be appreciated.

**Comment by greypants** [comment]
Hm... some dependencies were updated recently. I'll take a look. Are you having the same issue on the [2.0 branch](https://github.com/greypants/gulp-starter/tree/2.0)?

**Comment by deefour** [comment]
Something within the `watchify` task is blocking/hanging, preventing the watchers in the watch task itself from kicking off.

With `watchify` removed from the list of dependent tasks in `watch.js`, the task runs fine and styles, images, markup are all updated through browserSync as expected. This isn't a fix of course; just helping pinpoint the cause.

**Comment by deefour** [comment]
@greypants [`2.0`](https://github.com/greypants/gulp-starter/tree/2.0) works fine. `master` doesn't.

**Comment by greypants** [comment]
Fixed! Sorry about that.

**Comment by joachimgit** [comment]
It seems you added a lot of garbage in that commit.

**Comment by greypants** [comment]
crap. thats why pullrequests.

**Comment by greypants** [comment]
Fixed. thanks @joachimgit

**Comment by joachimgit** [comment]
Thanks,
but now the standalone browserify task is broken and never ends since the single parameter (devMode) acts as the callback function.
Maybe redefining the browserify task with a new function that call the old one would be enough?

**Comment by greypants** [comment]
ugh. good catch.

**Comment by deefour** [comment]
Thanks for the quick fix, @greypants.

**Comment by mehtmehtsen** [comment]
Woah, that was quick! Thanks, @greypants!

**Comment by greypants** [comment]
:+1: Thanks for the feedback.

**Comment by gandhiShepard** [comment]
Badass! Stay awesome!

**Comment by gandhiShepard** [comment]
![hqbjc](https://cloud.githubusercontent.com/assets/8546059/6750131/399be642-cec5-11e4-9d9e-dc58a9fa9c8c.gif)
