### ISSUE TITLE
How can I add jquery plugin in project

### ISSUE THREAD

**Issue by lkdnvc** [greypants/gulp-starter#117]
How can I add jquery plugin in project

**Comment by lan3jur** [comment]
The same way as you do in your project.
Basically, what I sent you is a simple gulp-plugin, similar to gulp-sequence, but instead of reading tasks from your gulpfile, it reads them from tasks.json

so instead of writing

gulp.task(‘build’, function () {
	gulpSequence(‘clean’, [‘jade’, ‘stylus’], scripts, callback);
}

you write

var tasks	= require(‘jsonTasks’);

gulp.task(‘build’, function () {
	jsonTasks(tasks, callback);
}

Let me know if you have any more questions...

—
Nieuw email adres! Gelieve je adresboek bij te werken.
New email! Please update your contacts.

Jürgen Landrie
jurgen@codebakery.co

**Comment by greypants** [comment]
There's an example of this in the repo. First, you'll want to use browserify-shim to make the plugin commonJS compatible, and specify jQuery as a dependency of it.  I'm doing that in my `package.json` on the following lines: [Line 21](https://github.com/greypants/gulp-starter/blob/master/package.json#L21) and  [Lines 30-36](https://github.com/greypants/gulp-starter/blob/master/package.json#L30-L36)

After that, you just require the plugin wherever it gets used: https://github.com/greypants/gulp-starter/blob/e56fedc6110917339f4c0747a5ab3f184b750872/src/javascript/view.coffee#L4

Check out (browserify-shim)[https://github.com/thlorenz/browserify-shim] for more docs and examples.

**Comment by lan3jur** [comment]
Sorry about my previous mail..
Was not meant for this project :(
>

**Comment by greypants** [comment]
@lan3jur haha. That's ok. I figured.
