### ISSUE TITLE
How to include CSS from node_modules?

### ISSUE THREAD

**Issue by sondreb** [greypants/gulp-starter#124]
Node modules such as Angular Material have both JavaScript and stylesheet, how does one include the css files if not relying on scss? (I'm using Stylus).

**Comment by renestalder** [comment]
In most situations I copy the content of the CSS file to include and create a stylus file in a `vendors` subfolder of my styles, handling it manually to get full control over minification and concat.

In some projects I added them via @import, but since most pre-compilers output the @import as is and, it would just reference the original CSS file, adding another server request.

There are extensions to let @import include the file contents, but I didn't test kind of that.

**Comment by rstormsf** [comment]
@sondreb 
You can copy/paste from `node_modules` to `stylesheets` folder and let's say create `vendor` folder in there, and rename that `.css` file to `.scss` and add `@import` in `global.sass` 
FYI - I'm on `branch 2.0`

**Comment by sondreb** [comment]
Thanks for the suggestions, I ended up manually copying the .css files and rename into .styl (using Stylus).

**Comment by nhunzaker** [comment]
This issue is closed, but I thought I'd mention that `node-sass` has an `--include-path` option. You could use it to include `node_modules` in the `@import` paths. 

I'm doing it for a couple of React libraries that have required stylesheets and it has worked very well so far.

**Comment by renestalder** [comment]
@nhunzaker That doesn't solve the problem. It only makes importing easier. But if you make a @import on a CSS file instead a SCSS file, you'll get a raw CSS @import, referencing the CSS file instead of importing it's contents. So you add an additional server request for every @import on CSS files. (Stylus makes it exactly the same way).

**Comment by nhunzaker** [comment]
@renestalder Ah, sorry. For whatever reason I missed this detail. Without any pre/post processing help, you are correct.

**Comment by rstormsf** [comment]
So, what is the solution?

**Comment by renestalder** [comment]
@rstormsf You already named it. Or using third party tools.

**Update:**

While searching for references of third-party packages that are able to this, I stumbled over a issue in the Stylus repository. It seems there were changes recently made to the Stylus docs, adding a missing feature which wasn't documented yet.

You can add the `--include-css` parameter to make stylus copy/paste the contents of a CSS file.

See issue
stevelacy/gulp-stylus#95

And the parameter documentation here.
https://learnboost.github.io/stylus/docs/executable.html

And here is a gulp example:

```
gulp.src('./app/styl/style.styl')
    .pipe(stylus({
        'include css': true
    }))
    .pipe(gulp.dest('./dist/css'));
```
