### ISSUE TITLE
Native JavaScript source maps

### ISSUE THREAD

**Issue by gigablox** [greypants/gulp-starter#51]
Here are two tests.

1. The first test a `console.log("waht")` is executed in `app.controller.js`. What I notice is a link instead to the concatenated *Browserify'd* file `app.js`.

2. I am forcing an *undefined* error, right underneath this `console.log("waht")` also in `app.controller.js`. Also being linked to `app.js`

Am I wrong to expect these should both link to `app.controller.js`?

![hum](http://imgur.com/X9pLtKB.png)

On a side note, I was thinking about giving https://github.com/thlorenz/exorcist a try. 

How would I integrate that into the *Browserify* solution that exists now?

**Comment by greypants** [comment]
Sorry, I can't replicate that issue. Source maps work fine with native js for me:

![image](https://cloud.githubusercontent.com/assets/647549/5604308/a12ae1e2-9382-11e4-94ee-4c7e46184a11.png)

Source maps work for sure in Chrome devTools, and I *think* Firefox, but I'm not sure. Also, make sure devTools are open before the page loads (or hit refresh). Otherwise, it'll just link to the compiled files.
