### ISSUE TITLE
Switch out require(underscore) for lodash

### ISSUE THREAD

**Issue by hawkrives** [greypants/gulp-starter#90]
We require lodash in the package, but import underscore somewhere. 

That's the source of these "cannot find underscore" issues recently.

**Comment by hawkrives** [comment]
I'll make a pull request later.

**Comment by hawkrives** [comment]
Except that, having located the offending `require('underscore')`, I find myself at a loss as to what purpose it serves.

There's a comment in `package.json` that goes:

> The following 'underscore' example demonstrates exposing a module included by another module. If you were to `npm install underscore` separately and `require('underscore')`, you'd end up with two copies in your bundle. The one you installed, and the one that shipped with another package (backbone in this example). This is an edge case and should rarely happen.

> The 'plugin' example makes that file requireable with `require('plugin')`, and available to browserify-shim as 'plugin' on line 30.

If I understand this correctly, it's saying that ... well, I haven't actually figured it out. How would backbone be installing its own copy of underscore without npm or bower?

I guess I'm asking, what purpose does this aliasing of `underscore` to `backbone/node_modules/underscore` accomplish?

**Comment by greypants** [comment]
so when you `npm install backbone`, it brings its own copy of underscore with it. You can see it if you open up `node_modules/backbone` - you'll see underscore in there. If the only thing you required in a js file was `backbone`, and you opened up the compiled file, you'd see backbone.js AND underscore.js in the bundle. If you also `npm install underscore`, and `require 'underscore'`, you'd end up with backbone's copy + the copy you installed from npm. It's an edge case  I ran into, and I thought I'd call it out here. I know it's not super clear though. I may end up yanking that example since most people just get confused by it. Make sense?

**Comment by hawkrives** [comment]
That does make sense now.

...

It also sheds more light on [your comment the other day](https://github.com/greypants/gulp-starter/issues/87#issuecomment-71541208). Thanks for the followup!
