### ISSUE TITLE
Rename markup to html

### ISSUE THREAD

**Issue by danielcompton** [greypants/gulp-starter#93]
I found markup to be a little bit of a tricky name for the gulp task, it took me a little bit of thinking to realise that it meant HTML markup. While I understand that markup is technically correct and encompasses other markup languages as well as HTML, IMO HTML is a better name.

At the least I would suggest a comment on the markup task to explain it. I'm happy to make a PR for either option if you like.

**Comment by renestalder** [comment]
I see your point, but I think markup fits best since the markup file doesn't have to be HTML. For example, in my projects the markup task copies WordPress PHP files which hold the HTML markup with some PHP logic, thus markup fits better in my case. Even the PHP files hold HTML and PHP code, I would search for HTML files when the task reads HTML.

It could also be a handlebar, xaml, xml or different markup similar language.

Anyway the task does nothing more than copying files at the moment. It could also be named "copy", as most grunt repositories do.

**Comment by greypants** [comment]
All valid points. Yeah, the plan was to actually make that `markup` task do something more than copy, but I never got around to it. When I (or someone else) does, I'm fine with renaming the task to `html`.

**Comment by greypants** [comment]
All valid points. Yeah, the plan was to actually make that `markup` task do something more than copy, but I never got around to it. When I (or someone else) does, I'm fine with renaming the task to `html`. Whatever markup language you're using, it's going to get compiled to html. So it makes sense to me, but don't feel strongly about it.

**Comment by greypants** [comment]
Coming soon in: https://github.com/greypants/gulp-starter/tree/2.0
